import { useState } from 'react'
import { Copy, Edit3, Plus, Search, Trash2, UserCog } from 'lucide-react'

type Staff = { id: number; name: string; email: string; role: string; department: string; status: 'نشط' | 'موقوف' }
const seed: Staff[] = [
  { id: 1, name: 'أحمد محمد', email: 'ahmed@xeria-eg.com', role: 'مدير المركز', department: 'الإدارة', status: 'نشط' },
  { id: 2, name: 'منى حسن', email: 'mona@xeria-eg.com', role: 'طبيب', department: 'الأطفال', status: 'نشط' },
  { id: 3, name: 'سارة علي', email: 'sara@xeria-eg.com', role: 'تمريض', department: 'التمريض', status: 'نشط' },
  { id: 4, name: 'خالد سمير', email: 'khaled@xeria-eg.com', role: 'استقبال', department: 'الاستقبال', status: 'موقوف' },
]
export default function Users() {
  const [rows, setRows] = useState(seed); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [bulk, setBulk] = useState('')
  const [form, setForm] = useState({ name: '', email: '', role: 'طبيب', department: 'الباطنة' })
  const filtered = rows.filter(row => `${row.name} ${row.email} ${row.role} ${row.department}`.includes(search))
  const add = () => { if (!form.name || !form.email) return; setRows(current => [...current, { ...form, id: Date.now(), status: 'نشط' }]); setForm({ name: '', email: '', role: 'طبيب', department: 'الباطنة' }); setShowForm(false) }
  const pasteBulk = () => { const additions = bulk.split('\n').map(line => line.split(',')).filter(parts => parts[0] && parts[1]).map(parts => ({ id: Date.now() + Math.random(), name: parts[0].trim(), email: parts[1].trim(), role: parts[2]?.trim() || 'طبيب', department: parts[3]?.trim() || 'عام', status: 'نشط' as const })); setRows(current => [...current, ...additions]); setBulk('') }
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-brand-700">صلاحيات فريق المركز</p><h1 className="mt-1 text-3xl font-bold">إدارة المستخدمين</h1><p className="mt-2 text-slate-500">إضافة منفردة أو نسخ ولصق عدة مستخدمين دفعة واحدة.</p></div><button onClick={() => setShowForm(true)} className="btn-primary"><Plus size={18} /> إضافة مستخدم</button></header>
    <div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><section className="card"><div className="flex items-center gap-3"><Copy className="text-brand-700" size={19} /><div><h2 className="font-bold">إضافة جماعية</h2><p className="text-xs text-slate-500">كل سطر: الاسم، البريد، الدور، القسم</p></div></div><textarea value={bulk} onChange={e => setBulk(e.target.value)} className="input mt-4 min-h-24" placeholder="محمود حسن, mahmoud@example.com, تمريض, التمريض" /><button onClick={pasteBulk} disabled={!bulk.trim()} className="btn-ghost mt-3">إضافة القائمة</button></section><section className="card"><div className="flex items-center gap-3"><UserCog className="text-sky-700" size={19} /><div><h2 className="font-bold">توزيع الصلاحيات</h2><p className="text-xs text-slate-500">الأدوار جاهزة وقابلة للتغيير</p></div></div><div className="mt-4 flex flex-wrap gap-2">{['مدير المركز', 'طبيب', 'تمريض', 'استقبال', 'محاسب'].map(role => <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600" key={role}>{role}</span>)}</div></section></div>
    {showForm && <div className="card border-brand-200"><div className="grid gap-3 sm:grid-cols-2"><input className="input" placeholder="اسم المستخدم" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><input className="input" type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><select className="input" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}>{['مدير المركز', 'طبيب', 'تمريض', 'استقبال', 'محاسب'].map(x => <option key={x}>{x}</option>)}</select><input className="input" placeholder="القسم" value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} /></div><div className="mt-3 flex gap-2"><button onClick={add} className="btn-primary">حفظ المستخدم</button><button onClick={() => setShowForm(false)} className="btn-ghost">إلغاء</button></div></div>}
    <section className="card overflow-hidden p-0"><div className="flex items-center gap-3 border-b border-slate-100 p-4"><Search size={18} className="text-slate-400" /><input className="w-full outline-none" placeholder="بحث في المستخدمين" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="divide-y divide-slate-100">{filtered.map(row => <div className="flex flex-wrap items-center gap-3 px-5 py-4" key={row.id}><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-50 font-bold text-brand-700">{row.name.slice(0, 2)}</span><div className="min-w-40 flex-1"><p className="font-semibold">{row.name}</p><p className="text-xs text-slate-500">{row.email}</p></div><span className="text-sm text-slate-600">{row.role}</span><span className="text-sm text-slate-500">{row.department}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${row.status === 'نشط' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'}`}>{row.status}</span><button aria-label="تعديل" className="text-slate-400 hover:text-brand-700"><Edit3 size={17} /></button><button aria-label="حذف" onClick={() => setRows(current => current.filter(item => item.id !== row.id))} className="text-slate-400 hover:text-rose-600"><Trash2 size={17} /></button></div>)}</div></section></div>
}
